/**
 * 默认密钥检测规则
 */

import { SecretPattern } from '@/types/config.d';

export const DEFAULT_SECRET_PATTERNS: SecretPattern[] = [
  {
    id: 'id_card',
    name: '二代身份证',
    description: '检测中国二代身份证号码',
    pattern: '\\b([1-9]\\d{5}(19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx])\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'phone',
    name: '手机号',
    description: '检测中国大陆手机号码',
    pattern: '\\b1[3-9]\\d{9}\\b',
    severity: 'medium',
    enabled: false,
    createdAt: Date.now(),
  },
  {
    id: 'jwt_token',
    name: 'JWT Token',
    description: '检测 JSON Web Token',
    pattern: 'eyJ[A-Za-z0-9_/+\\-]{10,}={0,2}\\.[A-Za-z0-9_/+\\-]{15,}={0,2}\\.[A-Za-z0-9_/+\\-]{10,}={0,2}',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'Aliyun_AK_ID',
    name: '阿里云 AccessKey ID',
    description: '检测阿里云 AccessKey ID',
    pattern: '\\bLTAI[A-Za-z\\d]{12,30}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'QCloud_AK_ID',
    name: '腾讯云 AccessKey ID',
    description: '检测腾讯云 AccessKey ID',
    pattern: '\\bAKID[A-Za-z\\d]{13,40}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'JDCloud_AK_ID',
    name: '京东云 AccessKey ID',
    description: '检测京东云 AccessKey ID',
    pattern: '\\bJDC_[0-9A-Z]{25,40}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'AWS_AK_ID',
    name: '亚马逊 AccessKey ID',
    description: '检测亚马逊 AWS AccessKey ID',
    pattern: '["\''](?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}["\'']',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'VolcanoEngine_AK_ID',
    name: '火山引擎 AccessKey ID',
    description: '检测火山引擎 AccessKey ID',
    pattern: '\\b(?:AKLT|AKTP)[a-zA-Z0-9]{35,50}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'Kingsoft_AK_ID',
    name: '金山云 AccessKey ID',
    description: '检测金山云 AccessKey ID',
    pattern: '\\bAKLT[a-zA-Z0-9\\-_]{16,28}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'GCP_AK_ID',
    name: '谷歌云 AccessKey ID',
    description: '检测 Google Cloud Platform API Key',
    pattern: '\\bAIza[0-9A-Za-z_\\-]{35}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'bearer_token',
    name: 'Bearer Token',
    description: '检测 Bearer 认证令牌',
    pattern: '\\b[Bb]earer\\s+[a-zA-Z0-9\\-=._+/\\\\]{20,500}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'basic_token',
    name: 'Basic Token',
    description: '检测 Basic 认证令牌',
    pattern: '\\b[Bb]asic\\s+[A-Za-z0-9+/]{18,}={0,2}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'auth_token',
    name: 'Auth Token',
    description: '检测 Authorization 令牌',
    pattern: '["\'\'\\[]*[Aa]uthorization["\'\'\\]]*\\s*[:=]\\s*[\'\'"]?\\b(?:[Tt]oken\\s+)?[a-zA-Z0-9\\-_+/]{20,500}[\'\'"]?',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'private_key',
    name: 'Private Key',
    description: '检测私钥文件内容',
    pattern: '-----\\s*?BEGIN[ A-Z0-9_-]*?PRIVATE KEY\\s*?-----[a-zA-Z0-9\\/\\n\\r=+]*-----\\s*?END[ A-Z0-9_-]*? PRIVATE KEY\\s*?-----',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'gitlab_v2_token',
    name: 'GitLab V2 Token',
    description: '检测 GitLab Personal Access Token V2',
    pattern: '\\b(glpat-[a-zA-Z0-9\\-=_]{20,22})\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'github_token',
    name: 'GitHub Token',
    description: '检测 GitHub Personal Access Token',
    pattern: '\\b((?:ghp|gho|ghu|ghs|ghr|github_pat)_[a-zA-Z0-9_]{36,255})\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'qcloud_api_gateway_appkey',
    name: '腾讯云 API 网关 APPKEY',
    description: '检测腾讯云 API 网关 APPKEY',
    pattern: '\\bAPID[a-zA-Z0-9]{32,42}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'wechat_appid',
    name: '微信公众号/小程序 APPID',
    description: '检测微信 APPID',
    pattern: '["\'\'](wx[a-z0-9]{15,18})["\'']',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'wechat_corpid',
    name: '企业微信 CorpID',
    description: '检测企业微信 CorpID',
    pattern: '["\'\'](ww[a-z0-9]{15,18})["\'']',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'wechat_id',
    name: '微信公众号 ID',
    description: '检测微信公众号唯一标识',
    pattern: '["\'\'](gh_[a-z0-9]{11,13})["\'']',
    severity: 'low',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'password',
    name: '密码字段',
    description: '检测配置中的密码字段',
    pattern: '(?i)(?:admin_?pass|password|[a-z]{3,15}_?password|user_?pass|user_?pwd|admin_?pwd)\\\\?[\'\'"]\\s*[:=]\\s*\\\\?[\'\'"][a-z0-9!@#$%&*]{5,20}\\\\?[\'\'"]',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'wechat_webhookurl',
    name: '企业微信 Webhook',
    description: '检测企业微信 Webhook URL',
    pattern: '\\bhttps://qyapi.weixin.qq.com/cgi-bin/webhook/send\\?key=[a-zA-Z0-9\\-]{25,50}\\b',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'dingtalk_webhookurl',
    name: '钉钉 Webhook',
    description: '检测钉钉 Webhook URL',
    pattern: '\\bhttps://oapi.dingtalk.com/robot/send\\?access_token=[a-z0-9]{50,80}\\b',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'feishu_webhookurl',
    name: '飞书 Webhook',
    description: '检测飞书 Webhook URL',
    pattern: '\\bhttps://open.feishu.cn/open-apis/bot/v2/hook/[a-z0-9\\-]{25,50}\\b',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'slack_webhookurl',
    name: 'Slack Webhook',
    description: '检测 Slack Webhook URL',
    pattern: '\\bhttps://hooks.slack.com/services/[a-zA-Z0-9\\-_]{6,12}/[a-zA-Z0-9\\-_]{6,12}/[a-zA-Z0-9\\-_]{15,24}\\b',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'grafana_api_key',
    name: 'Grafana API Key',
    description: '检测 Grafana API Key',
    pattern: '\\beyJrIjoi[a-zA-Z0-9\\-_+/]{50,100}={0,2}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'grafana_cloud_api_token',
    name: 'Grafana Cloud API Token',
    description: '检测 Grafana Cloud API Token',
    pattern: '\\bglc_[A-Za-z0-9\\-_+/]{32,200}={0,2}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'grafana_service_account_token',
    name: 'Grafana Service Account Token',
    description: '检测 Grafana Service Account Token',
    pattern: '\\bglsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8}\\b',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
  {
    id: 'app_key',
    name: '前端应用密钥',
    description: '检测前端应用配置中的密钥',
    pattern: '\\b(?:VUE|APP|REACT)_[A-Z_0-9]{1,15}_(?:KEY|PASS|PASSWORD|TOKEN|APIKEY)[\'\'"][:=]"(?:[A-Za-z0-9_\\-]{15,50}|[a-z0-9/+]{50,100}==?)"',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
  },
];
